Psychedelic/cover

services/cover/src/service/guard.rs

Update production blackhole
- Update production blackhole
- N/A

chore: 🚬 update ic blackhole

---

services/cover/cover.did
services/cover/src/lib.rs
services/cover/src/service/cover.rs
services/cover/src/service/store/verification.rs
services/cover/src/service/types.rs

submit verification.
- submit verification
- N/A

feat: 🎸 submit verification

---

canister_ids.json

IC cover canister ID
- IC cover canister ID
- N/A

feat: 🎸 IC cover canister ID

---

GithubActionPlugin/action.yaml
GithubActionPlugin/scripts/checksum-canister.sh
GithubActionPlugin/scripts/cover-verification.sh
serverless/app/package.json
serverless/app/src/functions/canister/publish/handler.ts

fix: Minor fixes, security update

---

services/cover/src/service/guard.rs
services/cover/src/service/store/canister_build_config.rs
services/cover/src/service/store/progress.rs
services/cover/src/service/store/provider.rs
services/cover/src/service/store/request.rs
services/cover/src/service/store/verification.rs

fix lint errors
- use Derive instead of implement Default for stores
- N/A

fix:lint errors

---

services/cover/Cargo.toml
services/cover/cover.did
services/cover/src/api/build_config.rs
services/cover/src/api/progress.rs
services/cover/src/api/provider.rs
services/cover/src/api/request.rs
services/cover/src/api/verification.rs
services/cover/src/lib.rs
services/cover/src/main.rs

auto generate candid file
- use export_service to generate candid file
- N/A

feat: auto generate candid file

---

services/cover/cover.did
services/cover/src/api/progress.rs
services/cover/src/api/provider.rs
services/cover/src/api/request.rs
services/cover/src/api/verification.rs
services/cover/src/service/build_config.rs
services/cover/src/service/guard.rs
services/cover/src/service/mod.rs
services/cover/src/service/model/request.rs
services/cover/src/service/progress.rs
services/cover/src/service/provider.rs
services/cover/src/service/request.rs
services/cover/src/service/store/request.rs
services/cover/src/service/store/test_data/add_request.rs
services/cover/src/service/store/test_data/create_request.rs
services/cover/src/service/store/test_data/mod.rs
services/cover/src/service/verification.rs

refactor code
- Rename services
- Rename api argument
- N/A

chore: refactor 

---

services/cover/cover.did
services/cover/src/api/build_config.rs
services/cover/src/service/build_config.rs
services/cover/src/service/error_handler.rs
services/cover/src/service/mod.rs
services/cover/src/service/model/build_config.rs
services/cover/src/service/model/error.rs
services/cover/src/service/store/build_config.rs
services/cover/src/service/store/mod.rs
services/cover/src/service/store/test_data/add_build_config.rs
services/cover/src/service/store/test_data/build_config.rs
services/cover/src/service/store/test_data/mod.rs
services/cover/src/service/store/test_data/update_build_config.rs

unit test for all api
- write unit test for all api
- add update and add model for build_config
- N/A

test: api unit test

---

Cargo.lock
services/cover/Cargo.toml
services/cover/cover.did
services/cover/src/api/admin.rs
services/cover/src/api/build_config.rs
services/cover/src/api/progress.rs
services/cover/src/api/provider.rs
services/cover/src/api/request.rs
services/cover/src/api/verification.rs
services/cover/src/service/build_config.rs
services/cover/src/service/error_handler.rs
services/cover/src/service/guard.rs
services/cover/src/service/model/provider.rs
services/cover/src/service/progress.rs
services/cover/src/service/provider.rs
services/cover/src/service/request.rs
services/cover/src/service/store/build_config.rs
services/cover/src/service/store/progress.rs
services/cover/src/service/store/provider.rs
services/cover/src/service/store/request.rs
services/cover/src/service/store/test_data/add_provider.rs
services/cover/src/service/store/test_data/add_request.rs
services/cover/src/service/store/test_data/add_verification.rs
services/cover/src/service/store/test_data/mod.rs
services/cover/src/service/store/test_data/provider.rs
services/cover/src/service/store/test_data/update_progress.rs
services/cover/src/service/store/test_data/update_provider.rs
services/cover/src/service/store/test_data/update_verification.rs
services/cover/src/service/store/verification.rs
services/cover/src/service/verification.rs

unit test for provider api, create provider guard
- unit test for provider api
- create provider guard
- N/A

test: unit test for provider api, create provider guard

---

src/api/verification.rs
src/service/model/verification.rs
src/service/store/test_data/mod.rs
src/service/store/test_data/submit_verification.rs
src/service/store/test_data/verification.rs

unit test for verification api
- unit test for verification api
- add more test data
- N/A

test: unit test for verification api

---

src/api/build_config.rs
src/api/provider.rs
src/api/verification.rs
src/service/store/build_config.rs
src/service/store/test_data/build_config.rs
src/service/store/test_data/provider.rs
src/service/store/test_data/update_build_config.rs
src/service/store/test_data/verification.rs

update unit tests
- Update verification, build config, provider unit tests
- Update test data
- N/A

fix: update unit tests

---

.github/workflows/pr_check.yml

Create pr_check.yml
- Create pr_check.yml
- N/A

feat: create pr_check.yml

---

.github/workflows/pr_check.yml
src/api/build_config.rs
src/service/store/admin.rs
src/service/store/build_config.rs
src/service/store/progress.rs
src/service/store/verification.rs

fix lint errors
- fix lint errors
- N/A

fix: lint errors

---

.github/workflows/pr_check.yml

update yml file
- update yml file
- N/A

chore: update yml

---

.github/workflows/security_audit.yml

add security audit
- add security audit yml file
- N/A

feat: add security audit

---

.github/workflows/cover_build.yml
.github/workflows/pr_check.yml
tools/docker/dockerfile

create build.yml
- create build.yml file
- Done B
- N/A

feat: create build.yml

---

.github/workflows/cover_build.yml
tools/docker/dockerfile

update build yml
- update build yml
- N/A

feat: update build yml

---

dfx.json

update dfx.json
- update dfx.json
-N/A

chore: update dfx.json

---

.github/workflows/cover_build.yml

add dfx type validator to cover builder
- add dfx type validator to cover builder
- [24732](https://app.shortcut.com/terminalsystems/story/24732/validate)

feat: add dfx type validator to cover builder

---

.github/workflows/cover_build.yml

Clear and short explanation here.
- Done A (replace with a breakdown of the steps)
- Done B
- [Ticket 1](the-ticket-url-here)

feat: update builder

---

cover.did
src/service/model/build_config.rs
src/service/store/build_config.rs
src/service/store/test_data/build_config.rs
src/service/store/test_data/save_build_config.rs

update build config model
- update build config model
- [24736](https://app.shortcut.com/terminalsystems/story/24736/update-data-model)

chore: update build config model

---

.github/workflows/cover_build.yml
cover.did
src/api/build_config.rs
src/api/provider.rs
src/api/verification.rs
src/service/model/build_config.rs
src/service/model/verification.rs
src/service/provider.rs
src/service/store/provider.rs
src/service/store/test_data/submit_verification.rs
src/service/store/test_data/verification.rs
src/service/store/verification.rs
src/service/verification.rs

- refactor build config & verification
- refactor build config & verification model and unit test
- N/A

chore: refactor

---

README-DEV.md
README.temp.md
cover.did
src/api/mod.rs
src/api/test.rs
src/service/model/error.rs
src/service/model/mod.rs
src/service/model/provider.rs

add readme temp
- Add readme temp
- [24731](https://app.shortcut.com/terminalsystems/story/24731/document)

chore: add readme temp

---

cover.did
src/api/verification.rs
src/main.rs
src/service/mod.rs
src/service/model/mod.rs
src/service/model/pagination.rs
src/service/pagination.rs
src/service/store/test_data/mod.rs
src/service/store/test_data/pagination.rs
src/service/store/verification.rs
src/service/verification.rs

- support pagination
- add pagination
- support get verification with pagination
- [24862](https://app.shortcut.com/terminalsystems/story/24862/pagination)

feat: pagination

---

cover.did
src/api/activity.rs
src/api/mod.rs
src/main.rs
src/service/activity.rs
src/service/mod.rs
src/service/model/activity.rs
src/service/model/mod.rs
src/service/model/verification.rs
src/service/store/activity.rs
src/service/store/mod.rs
src/service/store/test_data/activity.rs
src/service/store/test_data/mod.rs

- add activity
- implement activity store, service, api, unit test
- [25315](https://app.shortcut.com/terminalsystems/story/25315/activity)

feat: add activity

---

src/main.rs
src/service/guard.rs

feat: init admin

---

cover.did
src/api/activity.rs
src/api/admin.rs
src/api/build_config.rs
src/api/builder.rs
src/api/validator.rs
src/api/verification.rs
src/common/types.rs
src/main.rs
src/service/activity.rs
src/service/admin.rs
src/service/build_config.rs
src/service/builder.rs
src/service/model/error.rs
src/service/model/mod.rs
src/service/model/verification.rs
src/service/store/activity.rs
src/service/store/admin.rs
src/service/store/build_config.rs
src/service/store/builder.rs
src/service/store/test_data/activity.rs
src/service/store/test_data/mod.rs
src/service/store/test_data/register_verification.rs
src/service/store/test_data/submit_verification.rs
src/service/store/test_data/verification.rs
src/service/store/validator.rs
src/service/store/verification.rs
src/service/validator.rs
src/service/verification.rs

register verification.
- register verification
- [24741](https://app.shortcut.com/terminalsystems/story/24741/adjust-backend-logic)

feat: register verification

---

cover.did
src/service/model/build_config.rs
src/service/store/build_config.rs
test/dist/factory/idl.js
test/factory/idl.d.ts
test/factory/idl.ts

- refactor build config model
- remove create_at
- N/A

chore: refactor build config model

---

README-DEV.md

- update README dev
- update integration test command for README-DEV
- N/A

chore: update integration test README-DEV

---

src/service/model/activity.rs
src/service/model/build_config.rs
src/service/model/error.rs
src/service/model/pagination.rs
src/service/model/stats.rs
src/service/model/verification.rs

- refactor derive
- delete unnecessary derive
- N/A

chore: refactor derive

---

src/service/store/mod.rs

- update upgrade function
- update upgrade function
- N/A

chore: update upgrade function

---

tools/docker/cover-dockerfile

update dockerfile.
- update dockerfile
- 
- [Ticket 1](the-ticket-url-here)

chore: update dockerfile

---

Cargo.lock
Cargo.toml
dfx.json
tools/docker/cover-dockerfile

pump version
- pump version
- NA

chore: pump version

---

Cargo.lock
dfx.json

chore: pump dfx

---

canister_name.sh
cover.did
dfx.json
src/main.rs
src/model/cover_metadata.rs
src/model/mod.rs
test/factory/idl.d.ts
test/factory/idl.ts

cover metadata.
- cover metadata
- N/A

feat: cover metadata

---

Makefile
README-DEV.md

deployment tools.
- deployment tools
- N/A

feat: deploy

---

cover.did
src/main.rs
src/model/activity.rs
src/store/activity.rs
src/store/mod.rs
src/store/verification.rs
test/idl/cover.did.d.ts
test/idl/cover.did.ts
test/integration/cover.test.ts

my activities.
- my activities.
- N/A

feat: my activities

---

cover.did
src/main.rs
src/model/cover_metadata.rs
test/.eslintrc.json
test/idl/cover.did.d.ts
test/idl/cover.did.ts
test/integration/cover.test.ts

improve coverMetadata.
- improve coverMetadata
- N/A

chore: improve coverMetadata
